spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - args:
            - (cd /custom-tools && wget https://github.com/ahadas/syncset-gen/releases/download/demo1/ss
              && chmod +x ss)
          command:
            - sh
            - -c
          image: alpine:3.8
          imagePullPolicy: IfNotPresent
          name: download-tools2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/ss
              name: custom-tools
              subPath: ss